export enum DriverDocumentTypeEnum {
  DRIVER_LICENSE = 'DRIVER_LICENSE',
  VEHICLE_REGISTRATION = 'VEHICLE_REGISTRATION',
  INSURANCE = 'INSURANCE',
  ID_CARD = 'ID_CARD',
  MEDICAL_CLEARANCE = 'MEDICAL_CLEARANCE',
}
